[workspace]
authors = ["michael zhanay <mzhanay@bnl.gov>"]
channels = ["conda-forge"]
name = "fast-track-2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
click = "8.2.1.*"
fastapi = "0.116.1.*"
